### ISSUE TITLE
num_classes=2？num_classes=4？

### ISSUE THREAD

**Issue by navy63** [zhulf0804/UNet-Tensorflow#3]
请问这个num_classes，应该是2还是4，我怎么理解应该是2，你这里写的全部都是4，不是两分类么，0和1，那如果4分类，数据集该怎么制作

**Comment by zhulf0804** [comment]
这个是都可以的。4分类的话数据集的像素的标签就是0,1,2,3。

**Comment by zhulf0804** [comment]
> 请问这个num_classes，应该是2还是4，我怎么理解应该是2，你这里写的全部都是4，不是两分类么，0和1，那如果4分类，数据集该怎么制作

num_classes设置成2和4都可以。如果是4分类，数据集中像素的标签对应的是0,1,2,3。
